name: $(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: "vs2017-win2016"
jobs:
- job: Build
  steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      configFilePath: 'GitVersion.yml'
      updateAssemblyInfo: true
      updateAssemblyInfoFilename: 'src/SharedAssemblyInfo.cs'
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '5.2.0'
      checkLatest: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      configuration: '$(BuildConfiguration)'
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'GitVersion.NuGetVersion'
      includeSymbols: true
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '**/Leprechaun.Console.Runner.nuspec'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'GitVersion.NuGetVersion'
      includeSymbols: true
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '8e7d8e9a-96b7-4364-985a-625841ad216e/f096d8c4-c6ef-4c3f-ab64-f47f1c625b2e'